parent=keycloak

# Nenastavujeme styles= — dědíme login.css z parent keycloak tématu
# Custom CSS přidáváme přímo v template.ftl

stylesCommon=web_modules/@patternfly/react-core/dist/styles/base.css web_modules/@patternfly/react-core/dist/styles/app.css

locales=en, cs
